name: Issue Handler

on:
  issues:
    types: [opened]

jobs:
  handle-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Branch
        run: |
          git config --global user.email "issuebot@learnprompting.com"
          git config --global user.name "Issue Bot"
          git checkout -b issue-${{ github.event.issue.number }}
          git commit --allow-empty -m "Created branch to fix issue #${{ github.event.issue.number }}"
          git push origin issue-${{ github.event.issue.number }}

      - name: Create Pull Request
        run: gh pr create -B "main" -H "issue-${{ github.event.issue.number }}" --title "Pr to Fix Issue ${{ github.event.issue.number }} - ${{ github.event.issue.title }}" --body "Created by Github actions, fixes ${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
